version: "3.7"
services:
  database:
    container_name: aperture-database
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: America/Phoenix
    image: postgres:14.2-alpine
    ports:
      - ${PORT_DATABASE}:5432
    restart: unless-stopped
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  migrations:
    command: [ '--wait', '--no-dump-schema', 'up' ]
    container_name: aperture-migrations
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
    image: ghcr.io/amacneil/dbmate
    volumes:
      - ./db:/db

  service-authentication:
    build:
      context: .
      dockerfile: ./packages/service-authentication/Dockerfile
    container_name: aperture-service-authentication
    depends_on:
      - database
      - service-logger
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      DOMAIN: ${DOCKER_DOMAIN}
    ports:
      - ${PORT_SERVICE_AUTHENTICATION}:${PORT_SERVICE_AUTHENTICATION}
    restart: unless-stopped

  service-logger:
    build:
      context: .
      dockerfile: ./packages/service-logger/Dockerfile
    container_name: aperture-service-logger
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      DOMAIN: ${DOCKER_DOMAIN}
    ports:
      - ${PORT_SERVICE_LOGGER}:${PORT_SERVICE_LOGGER}
    restart: unless-stopped
