export type ScreenParams = {
  Appointments: undefined,
  AppointmentDetails: { id: number },
  AppointmentPassport: { id: number },
  AppointmentSearch: undefined,
  Authenticated: undefined,
  BookNow: undefined,
  ForgotPassword: undefined,
  Login: undefined,
  Profile: undefined,
  Signup: undefined,
  SignupAddress: undefined,
  SignupContact: undefined,
  SignupDemographics: undefined,
  SignupInsurance: undefined,
  SignupPrivacyPolicy: undefined,
  SignupTermsOfService: undefined,
  Support: undefined,
};
